pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'mightyseveri/severi-temperatureconverter-pipeline'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('temperatureConverter') {
                    sh 'mvn clean install'
                }
            }
        }

        stage('Test') {
            steps {
                dir('temperatureConverter') {
                    sh 'mvn test'
                }
            }
        }

        stage('Code Coverage') {
            steps {
                dir('temperatureConverter') {
                    sh 'mvn jacoco:report'
                }
            }
        }

        stage('Publish Test Results') {
            steps {
                junit 'temperatureConverter/target/surefire-reports/*.xml'
            }
        }

        stage('Publish Coverage Report') {
            steps {
                jacoco()
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('temperatureConverter') {
                    sh 'docker build -t $DOCKER_IMAGE:latest .'
                }
            }
        }

        stage('Run Docker Image') {
            steps {
                dir('temperatureConverter') {
                    sh 'docker run --rm $DOCKER_IMAGE:latest'
                }
            }
        }

        stage('Docker Hub Login') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: '224db388-8728-4443-b914-597f64f7db4b',
                        usernameVariable: 'DOCKER_USERNAME',
                        passwordVariable: 'DOCKER_PASSWORD'
                    )
                ]) {
                    sh '''
                        echo "$DOCKER_PASSWORD" | docker login \
                            --username "$DOCKER_USERNAME" \
                            --password-stdin
                    '''
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                sh 'docker push $DOCKER_IMAGE:latest'
            }
        }
    }
}
