pipeline {
    agent any

    options {
        skipDefaultCheckout(true)
        timestamps()
    }

    environment {
        DOCKER_IMAGE = 'mightyseveri/severi-temperatureconverter-pipeline'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Test') {
            steps {
                dir('temperatureConverter') {
                    sh 'mvn -B clean verify'
                }
            }
        }

        stage('Publish Test Results') {
            steps {
                junit 'temperatureConverter/target/surefire-reports/*.xml'
            }
        }

        stage('Publish Coverage') {
            steps {
                jacoco(
                    execPattern: 'temperatureConverter/target/*.exec',
                    classPattern: 'temperatureConverter/target/classes',
                    sourcePattern: 'temperatureConverter'
                )
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('temperatureConverter') {
                    sh 'docker build -t $DOCKER_IMAGE:latest .'
                }
            }
        }

        stage('Login to Docker Hub') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: '224db388-8728-4443-b914-597f64f7db4b',
                        usernameVariable: 'DOCKER_USERNAME',
                        passwordVariable: 'DOCKER_PASSWORD'
                    )
                ]) {
                    sh '''
                        echo "$DOCKER_PASSWORD" | \
                        docker login \
                            --username "$DOCKER_USERNAME" \
                            --password-stdin
                    '''
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                sh 'docker push $DOCKER_IMAGE:latest'
            }
        }
    }
}
